### ISSUE TITLE
Дублирование dependency

### ISSUE THREAD

**Issue by khda91** [JuliaSPb/LevelUp_Homework#2]
https://github.com/JuliaSPb/LevelUp_Homework/blob/7f770c6b28873beb225361debafa4836d9e43cdb/pom.xml#L18
https://github.com/JuliaSPb/LevelUp_Homework/blob/7f770c6b28873beb225361debafa4836d9e43cdb/pom.xml#L19
https://github.com/JuliaSPb/LevelUp_Homework/blob/7f770c6b28873beb225361debafa4836d9e43cdb/pom.xml#L20
https://github.com/JuliaSPb/LevelUp_Homework/blob/7f770c6b28873beb225361debafa4836d9e43cdb/pom.xml#L21
https://github.com/JuliaSPb/LevelUp_Homework/blob/7f770c6b28873beb225361debafa4836d9e43cdb/pom.xml#L22

В каких целях используется дублирование junit библиотеки?

**Comment by JuliaSPb** [comment]
Не знаю, я вставляла в файл только одну dependency. Возможно, вторую добавила IDEA?

**Comment by khda91** [comment]
Будте пожалуйста внимательнее)
