### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by khda91** [JuliaSPb/LevelUp_Homework#4]
https://github.com/JuliaSPb/LevelUp_Homework/blob/7f770c6b28873beb225361debafa4836d9e43cdb/src/main/java/ru/levelup/julia_kalujnaya/qa/homework_1/task_4/RTriangleProviderSimpleTest.java#L63

А есть ли ещё способ проверки на то, что треугольник является прямоугольным?

**Comment by JuliaSPb** [comment]
Посчитать координаты 3 векторов, образованных сторонами треугольника, и затем их попарные скалярные произведения. Если одно из произведений равно 0, то угол между данными векторами прямой.

**Comment by khda91** [comment]
Верно, закрываем вопрос)
